//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsyncDataLoading.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Order", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
    [System.SerializableAttribute()]
    public partial class Order : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> EmployeeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> FreightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> OrderDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrderIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> RequiredDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShipAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShipCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShipCountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShipNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShipPostalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShipRegionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ShipViaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ShippedDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerID {
            get {
                return this.CustomerIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerIDField, value) != true)) {
                    this.CustomerIDField = value;
                    this.RaisePropertyChanged("CustomerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> EmployeeID {
            get {
                return this.EmployeeIDField;
            }
            set {
                if ((this.EmployeeIDField.Equals(value) != true)) {
                    this.EmployeeIDField = value;
                    this.RaisePropertyChanged("EmployeeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Freight {
            get {
                return this.FreightField;
            }
            set {
                if ((this.FreightField.Equals(value) != true)) {
                    this.FreightField = value;
                    this.RaisePropertyChanged("Freight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> OrderDate {
            get {
                return this.OrderDateField;
            }
            set {
                if ((this.OrderDateField.Equals(value) != true)) {
                    this.OrderDateField = value;
                    this.RaisePropertyChanged("OrderDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderID {
            get {
                return this.OrderIDField;
            }
            set {
                if ((this.OrderIDField.Equals(value) != true)) {
                    this.OrderIDField = value;
                    this.RaisePropertyChanged("OrderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> RequiredDate {
            get {
                return this.RequiredDateField;
            }
            set {
                if ((this.RequiredDateField.Equals(value) != true)) {
                    this.RequiredDateField = value;
                    this.RaisePropertyChanged("RequiredDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShipAddress {
            get {
                return this.ShipAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.ShipAddressField, value) != true)) {
                    this.ShipAddressField = value;
                    this.RaisePropertyChanged("ShipAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShipCity {
            get {
                return this.ShipCityField;
            }
            set {
                if ((object.ReferenceEquals(this.ShipCityField, value) != true)) {
                    this.ShipCityField = value;
                    this.RaisePropertyChanged("ShipCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShipCountry {
            get {
                return this.ShipCountryField;
            }
            set {
                if ((object.ReferenceEquals(this.ShipCountryField, value) != true)) {
                    this.ShipCountryField = value;
                    this.RaisePropertyChanged("ShipCountry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShipName {
            get {
                return this.ShipNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ShipNameField, value) != true)) {
                    this.ShipNameField = value;
                    this.RaisePropertyChanged("ShipName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShipPostalCode {
            get {
                return this.ShipPostalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ShipPostalCodeField, value) != true)) {
                    this.ShipPostalCodeField = value;
                    this.RaisePropertyChanged("ShipPostalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShipRegion {
            get {
                return this.ShipRegionField;
            }
            set {
                if ((object.ReferenceEquals(this.ShipRegionField, value) != true)) {
                    this.ShipRegionField = value;
                    this.RaisePropertyChanged("ShipRegion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ShipVia {
            get {
                return this.ShipViaField;
            }
            set {
                if ((this.ShipViaField.Equals(value) != true)) {
                    this.ShipViaField = value;
                    this.RaisePropertyChanged("ShipVia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ShippedDate {
            get {
                return this.ShippedDateField;
            }
            set {
                if ((this.ShippedDateField.Equals(value) != true)) {
                    this.ShippedDateField = value;
                    this.RaisePropertyChanged("ShippedDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IOrderService")]
    public interface IOrderService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderService/GetRecords", ReplyAction="http://tempuri.org/IOrderService/GetRecordsResponse")]
        AsyncDataLoading.ServiceReference1.GetRecordsResponse GetRecords(AsyncDataLoading.ServiceReference1.GetRecordsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IOrderService/GetRecords", ReplyAction="http://tempuri.org/IOrderService/GetRecordsResponse")]
        System.IAsyncResult BeginGetRecords(AsyncDataLoading.ServiceReference1.GetRecordsRequest request, System.AsyncCallback callback, object asyncState);
        
        AsyncDataLoading.ServiceReference1.GetRecordsResponse EndGetRecords(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderService/GetRecordsCount", ReplyAction="http://tempuri.org/IOrderService/GetRecordsCountResponse")]
        AsyncDataLoading.ServiceReference1.GetRecordsCountResponse GetRecordsCount(AsyncDataLoading.ServiceReference1.GetRecordsCountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IOrderService/GetRecordsCount", ReplyAction="http://tempuri.org/IOrderService/GetRecordsCountResponse")]
        System.IAsyncResult BeginGetRecordsCount(AsyncDataLoading.ServiceReference1.GetRecordsCountRequest request, System.AsyncCallback callback, object asyncState);
        
        AsyncDataLoading.ServiceReference1.GetRecordsCountResponse EndGetRecordsCount(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecords", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetRecordsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int skipCount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int takeCount;
        
        public GetRecordsRequest() {
        }
        
        public GetRecordsRequest(int skipCount, int takeCount) {
            this.skipCount = skipCount;
            this.takeCount = takeCount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecordsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetRecordsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.ObjectModel.ObservableCollection<AsyncDataLoading.ServiceReference1.Order> GetRecordsResult;
        
        public GetRecordsResponse() {
        }
        
        public GetRecordsResponse(System.Collections.ObjectModel.ObservableCollection<AsyncDataLoading.ServiceReference1.Order> GetRecordsResult) {
            this.GetRecordsResult = GetRecordsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecordsCount", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetRecordsCountRequest {
        
        public GetRecordsCountRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecordsCountResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetRecordsCountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int GetRecordsCountResult;
        
        public GetRecordsCountResponse() {
        }
        
        public GetRecordsCountResponse(int GetRecordsCountResult) {
            this.GetRecordsCountResult = GetRecordsCountResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOrderServiceChannel : AsyncDataLoading.ServiceReference1.IOrderService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetRecordsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetRecordsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public AsyncDataLoading.ServiceReference1.GetRecordsResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((AsyncDataLoading.ServiceReference1.GetRecordsResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetRecordsCountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetRecordsCountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public AsyncDataLoading.ServiceReference1.GetRecordsCountResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((AsyncDataLoading.ServiceReference1.GetRecordsCountResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrderServiceClient : System.ServiceModel.ClientBase<AsyncDataLoading.ServiceReference1.IOrderService>, AsyncDataLoading.ServiceReference1.IOrderService {
        
        private BeginOperationDelegate onBeginGetRecordsDelegate;
        
        private EndOperationDelegate onEndGetRecordsDelegate;
        
        private System.Threading.SendOrPostCallback onGetRecordsCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetRecordsCountDelegate;
        
        private EndOperationDelegate onEndGetRecordsCountDelegate;
        
        private System.Threading.SendOrPostCallback onGetRecordsCountCompletedDelegate;
        
        public OrderServiceClient() {
        }
        
        public OrderServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrderServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<GetRecordsCompletedEventArgs> GetRecordsCompleted;
        
        public event System.EventHandler<GetRecordsCountCompletedEventArgs> GetRecordsCountCompleted;
        
        public AsyncDataLoading.ServiceReference1.GetRecordsResponse GetRecords(AsyncDataLoading.ServiceReference1.GetRecordsRequest request) {
            return base.Channel.GetRecords(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetRecords(AsyncDataLoading.ServiceReference1.GetRecordsRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetRecords(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public AsyncDataLoading.ServiceReference1.GetRecordsResponse EndGetRecords(System.IAsyncResult result) {
            return base.Channel.EndGetRecords(result);
        }
        
        private System.IAsyncResult OnBeginGetRecords(object[] inValues, System.AsyncCallback callback, object asyncState) {
            AsyncDataLoading.ServiceReference1.GetRecordsRequest request = ((AsyncDataLoading.ServiceReference1.GetRecordsRequest)(inValues[0]));
            return this.BeginGetRecords(request, callback, asyncState);
        }
        
        private object[] OnEndGetRecords(System.IAsyncResult result) {
            AsyncDataLoading.ServiceReference1.GetRecordsResponse retVal = this.EndGetRecords(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetRecordsCompleted(object state) {
            if ((this.GetRecordsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetRecordsCompleted(this, new GetRecordsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetRecordsAsync(AsyncDataLoading.ServiceReference1.GetRecordsRequest request) {
            this.GetRecordsAsync(request, null);
        }
        
        public void GetRecordsAsync(AsyncDataLoading.ServiceReference1.GetRecordsRequest request, object userState) {
            if ((this.onBeginGetRecordsDelegate == null)) {
                this.onBeginGetRecordsDelegate = new BeginOperationDelegate(this.OnBeginGetRecords);
            }
            if ((this.onEndGetRecordsDelegate == null)) {
                this.onEndGetRecordsDelegate = new EndOperationDelegate(this.OnEndGetRecords);
            }
            if ((this.onGetRecordsCompletedDelegate == null)) {
                this.onGetRecordsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetRecordsCompleted);
            }
            base.InvokeAsync(this.onBeginGetRecordsDelegate, new object[] {
                        request}, this.onEndGetRecordsDelegate, this.onGetRecordsCompletedDelegate, userState);
        }
        
        public AsyncDataLoading.ServiceReference1.GetRecordsCountResponse GetRecordsCount(AsyncDataLoading.ServiceReference1.GetRecordsCountRequest request) {
            return base.Channel.GetRecordsCount(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetRecordsCount(AsyncDataLoading.ServiceReference1.GetRecordsCountRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetRecordsCount(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public AsyncDataLoading.ServiceReference1.GetRecordsCountResponse EndGetRecordsCount(System.IAsyncResult result) {
            return base.Channel.EndGetRecordsCount(result);
        }
        
        private System.IAsyncResult OnBeginGetRecordsCount(object[] inValues, System.AsyncCallback callback, object asyncState) {
            AsyncDataLoading.ServiceReference1.GetRecordsCountRequest request = ((AsyncDataLoading.ServiceReference1.GetRecordsCountRequest)(inValues[0]));
            return this.BeginGetRecordsCount(request, callback, asyncState);
        }
        
        private object[] OnEndGetRecordsCount(System.IAsyncResult result) {
            AsyncDataLoading.ServiceReference1.GetRecordsCountResponse retVal = this.EndGetRecordsCount(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetRecordsCountCompleted(object state) {
            if ((this.GetRecordsCountCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetRecordsCountCompleted(this, new GetRecordsCountCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetRecordsCountAsync(AsyncDataLoading.ServiceReference1.GetRecordsCountRequest request) {
            this.GetRecordsCountAsync(request, null);
        }
        
        public void GetRecordsCountAsync(AsyncDataLoading.ServiceReference1.GetRecordsCountRequest request, object userState) {
            if ((this.onBeginGetRecordsCountDelegate == null)) {
                this.onBeginGetRecordsCountDelegate = new BeginOperationDelegate(this.OnBeginGetRecordsCount);
            }
            if ((this.onEndGetRecordsCountDelegate == null)) {
                this.onEndGetRecordsCountDelegate = new EndOperationDelegate(this.OnEndGetRecordsCount);
            }
            if ((this.onGetRecordsCountCompletedDelegate == null)) {
                this.onGetRecordsCountCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetRecordsCountCompleted);
            }
            base.InvokeAsync(this.onBeginGetRecordsCountDelegate, new object[] {
                        request}, this.onEndGetRecordsCountDelegate, this.onGetRecordsCountCompletedDelegate, userState);
        }
    }
}
